### PR TITLE
Added Rust installer + Ansible Fixes.

### LINKED ISSUE #47: Install Rust
`curl https://sh.rustup.rs -sSf | sh`

- [ ] Create Pull Request
- [ ] https://opszero.typeform.com/to/JMnLYH

### PR DESCRIPTION
**Pull request by Kyle1668**
Closes #47

### CODE REVIEW

File: ami/base.sh [hunk 1]
```diff
@@ -70,11 +70,16 @@ sudo mv kubectl /usr/local/bin/kubectl
...
-sudo apt-get install software-properties-common
+sudo apt-get install software-properties-common -y
 sudo apt-add-repository ppa:ansible/ansible
 sudo apt-get update -y
 sudo apt-get install ansible -y
 
+# Install Rust
+echo "Just before Rust"
+sudo curl https://sh.rustup.rs -sSf | sh -y
+echo "Just after Rust"
```
Comment (abhiyerra) [inline ami/base.sh]: Remove the echos

**Comment by Kyle1668** [comment]
I was able to get rust working.

Previously I was using `curl https://sh.rustup.rs -sSf | sh` whish was not working.
`sudo curl -sf -L https://static.rust-lang.org/rustup.sh | sh` does however.

**Review by abhiyerra — APPROVED** [review]
LGTM. Add it to the release notes and merge
